### ISSUE TITLE
Plans to upstream?

### ISSUE THREAD

**Issue by ridingqwerty** [LeafCutterLabs/miniMACRO5#5]
Hey guys, cool project!

I'm one of the QMK collaborators, and a friend of mine who had purchased the miniMACRO5 reached out to me for help flashing it.  This being his first QMK project there was probably some confusion regarding our new user documentation and interacting with projects out of tree.

That said, we were able to get it sorted (I just added all the files under QMKv3/ to my branch and gave him the hex).  I was just wondering if there were plans to get this into the main QMK repo at some point for ease of flashing?

Thanks :)

**Comment by LeafCutterLabs** [comment]
Yes, I would love to have it in the main repo. How would I go about doing
that?

**Comment by ridingqwerty** [comment]
Great, that's awesome to hear!

The process is pretty straightforward -- generally you fork QMK (or if that's already done, get master updated), create a new branch, add in your changes, and then pull request to get your_fork:your_branch merged into QMK master.  Our process generally requires two collaborator approvals, but turnaround isn't too bad as long as you stay on top of any changes requested.

I'd say what you have already works pretty well -- I had no issues basically just copying everything in and building it as is.  There may need to be some minor concessions -- for example, not hosting the hardware files and having the README.md on the QMK repo be more focused on the firmware/flashing aspect -- but you could always link back to this repo from there so people would know where to find the hardware files and stuff.

I've already got a branch going on my end so if you want, I can PR it myself and tag you on it.  Let me know what you think.

**Comment by meaksb** [comment]
I just bought this board and I'm having a really hard time compiling my keymap file into a HEX when attempting to make a custom layout for it. It'd be really appreciated if you could streamline this process for people like me who have limited QMK experience. I've followed chokkan's video and it's still giving me errors :(

**Comment by LeafCutterLabs** [comment]
One problem is Configurator does not currently support encoders. Some problems with compiling have been case sensitivity issues. If you post your keymap I'm more than happy to compile and post it.

**Comment by dezlidezlidezli** [comment]
I have recently run a group-buy for this macropad, and am working on upstreaming this code. I will update this thread with the pull request number later, I'm still working on adjusting some code slightly.

**Comment by dezlidezlidezli** [comment]
https://github.com/qmk/qmk_firmware/pull/10392 alright, here is the pull request. I hope it gets merged quickly, I've done my best. Thank you @LeafCutterLabs for making this great macropad!

**Comment by dezlidezlidezli** [comment]
alright, @LeafCutterLabs... we can close this issue... your firmware has been merged into QMK main

**Comment by bsoll** [comment]
> 
> 
> alright, @LeafCutterLabs... we can close this issue... your firmware has been merged into QMK main

Awesome news! Just to clarify, it still won't support encoders for the Configurator right? What are our options for using encoders?

**Comment by LeafCutterLabs** [comment]
You can always compile local for encoder support.

**Comment by dezlidezlidezli** [comment]
Yes, unfortunately I cannot add VIA or QMK Configurator support because of the encoders. The layout appears pretty broken in the configurator, I didn’t see any use in fixing it as encoders wouldn’t work anyway. Once better encoder support is released, I will happily update QMK main. 

To program encoder functions yourself, you would do it in the same way as you would have previously with using files from this repository, but you won't need to work with extra remotes and it is part of the default QMK release. Customising the functions of this macro-pad (encoder or not) would mean editing it as if it was any other QMK file. 

The default key-map has placeholder key codes, for ease of customisation and to reduce confusion to those new to working with encoders or new to QMK. You can see the accompanying image [here](https://imgur.com/a/uPHNHCn), which will feature in a step by step key-map customisation guide specific to the miniMACRO5 guide which I am currently writing. 

The media key-map is basically the same as the one provided here in this repository. There were some changes made to the QMK firmware, to fit in with more modern practices recommended by the contributors to that repository. Notably, I have removed the RGB tap-dance parts of the software as I believe they were superfluous and something that can be added back later. I am soon going to be adding many custom user keycaps for members of my group-buy, where I will add back a clean default key-map copied right from this repository. 

I have put quite a lot of effort into documenting and improving the situation for this macro-pad since I have run a group-buy for it, I plan to offer some pull requests to this repository with improved documentation and hardware files. For example, I have redesigned the plate since the switch holes were the wrong size, I have access to V3c Gerber files sent to me by LeafCutterLabs and I have many other notes to add into documentation about how to program, build and manufacture this macro-pad. I am eager to share my improvements and findings with the public, when I get some time. 

If you think of a better solution for customisation, please let me know. I'm eager to work on bringing VIA or QMK Configurator support for this macro-pad once the support is there. Thank you!

PLEASE NOTE THAT I DO NOT HAVE PCBs IN HAND YET, I CAN SEE NO REASON IT WOULDN'T, BUT THE FIRMWARE UPSTREAM MAY NOT WORK. I WILL FIX THIS AND TEST THIS WHEN MY PCBs ARRIVE IN ABOUT 2 WEEKS.

**Comment by joncojonathan** [comment]
@dezlidezlidezli thanks for doing that.  It was on my list of things to do but then life happened and I've not been able to return to it.  I'll take a look at your QMK PR so I can see how to do the same for the other boards by @LeafCutterLabs.

Thanks for your contribution :) .
